# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e97a38f2526190e9a047e088dcea0fe179f8bcac87196a642ec88ff37e529ac93cdf3ff395ba5cbc51f2c0562d7e53c8d7614e5672ee63af3c4e095b612c136

test:
  secret_key_base: ac8e6a65fc22b3a9d27da6235698dbf798546f0f9320b320004fd24517dce4395f9bb53d7d9868143f78d1004aad50f3cec7eb0eee8952d55578c46a75f454cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
